### ISSUE TITLE
Using Counties Shape file

### ISSUE THREAD

**Issue by Brjax** [hunter-stanke/FGC_rFIA_SAE#1]
When running the code using the counties shape file (instead of grouping), the pop.est only returns ~ 100 records.

**Comment by Brjax** [comment]
> When running the code using the counties shape file (instead of grouping), the pop.est only returns ~ 100 records.

Resolved

**Comment by hunter-stanke** [comment]
Excellent, I was just about to recommend updating rFIA from GitHub. I assume that's what resolved the issue (NA groups in the shapefile were strictly dropped previously).

I'll be posting updates to this repo in the next couple days, including some more detailed tutorials. Just a heads up - stay tuned if interested.
